#!/bin/sh
echo "DW1820A网卡驱动信息："
echo "==========================================================="
echo "网卡型号："
ioreg -l | grep "14e4,43a3" | grep "compatible" | sed "s/|//g" | sed "s/ //g" 
echo "机型或者主板："
curl -fsSL https://raw.githubusercontent.com/daliansky/Hackintosh/master/Tools/bdmesg -o /tmp/bdmesg && chmod +x /tmp/bdmesg && sh -c /tmp/bdmesg | grep Running | awk '{print $3,$4,$5,$6,$7,$8,$9}' 
echo "PCI信息："
echo "=== [ GetDevices ] ========================================"
sh -c /tmp/bdmesg | grep PCI 
echo "驱动信息："
echo "==========================================================="
ioreg -l | grep "FirmwareVersionString" | sed "s/|//g" | sed "s/ //g" 
kextstat | grep -v com.apple | grep -y brcm | awk '{print $6,$7}'


