#!/bin/sh
# 
# @desc [Get DW1820A device information script]
# @author [DalianSky]
# @email [daliansky2008@mail.com]
# @create date 2020-01-5 05:12:13
# @modify date 2020-01-11 06:57:02
# 
# @command call： [ sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/Hackintosh/master/Tools/DW1820A)" ]

echo "macOS版本：" && sw_vers -productVersion
echo "==========================================================="
echo "机型或者主板："
curl -fsSL https://raw.githubusercontent.com/daliansky/Hackintosh/master/Tools/bdmesg -o /tmp/bdmesg && chmod +x /tmp/bdmesg && sh -c /tmp/bdmesg | grep Running
echo "=== [ GetDevices ] ========================================"
sh -c /tmp/bdmesg | grep PCI | grep -v IGPU | grep -v USBXHCI
echo "网卡信息："
echo "==========================================================="
curl -fsSL https://raw.githubusercontent.com/daliansky/Hackintosh/master/Tools/gfxutil -o /tmp/gfxutil && chmod +x /tmp/gfxutil && sh -c /tmp/gfxutil | grep ARPT | awk '{print $3}'
ioreg -l | grep "14e4,43" | grep "compatible" | sed "s/|//g" | sed "s/ //g" 
system_profiler SPAirPortDataType | grep "Card Type"
system_profiler SPAirPortDataType | grep "MAC Address"
echo "蓝牙信息："
echo "==========================================================="
system_profiler SPUSBDataType | grep BCM2045A0 | grep -v SPUSBDevice
ioreg -l | grep "FirmwareVersionString" | sed "s/|//g" | sed "s/ //g" 
kextstat | grep -v com.apple | grep -y brcm | awk '{print $6,$7}'


